### ISSUE TITLE
Does this package work with Python 3.6?

### ISSUE THREAD

**Issue by BlackArbsCEO** [QuantEcon/rvlib#14]
I'm trying to install using `conda` and am receiving the following error:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - rvlib -> python 3.5* -> xz 5.0.5
```

**Comment by sglyon** [comment]
Hmm, I haven't seen this  before, though I don't think I've used this library on python 3.6

It looks like the issue is with a package called xz. Have you researched anything about the xz package on Python 3.6? Maybe that would help?

**Comment by sglyon** [comment]
I don't believe rvlib uses the xz package directly. 

That makes things a little tricky to figure out how to work around this issue. 

Were you able to see any discussion online about why xz insists on Python 3,5?

**Comment by knaaptime** [comment]
builds for 3.6+ are available on conda-forge
