### ISSUE TITLE
Wrong mean for negative binomial

### ISSUE THREAD

**Issue by octoscore** [QuantEcon/rvlib#18]
Hi 

Something is wrong in the negative binomial distribution:

    from rvlib import NegativeBinomial as nbinom
    from rvlib import Poisson as poisson
    r = 10
    p = 0.2
    nb= nbinom(r,p)
    print (sum([nb.pdf(i)*i for i in range(10000)]),nb.mean)

 that print out 39.99 and 2.5.

The source code for the mean is

    @property
    def mean(self):
        """Return the mean."""
        return self.p*self.r/(1 - self.p)

 but the mean is clearly `(1-p)*r/(p)`. Looking [wikipedia ](https://en.wikipedia.org/wiki/Negative_binomial_distribution#Poisson_distribution) the pmf in the docstring is different so the mean should be corrected. I did not check the other formulas.

**Comment by sglyon** [comment]
Thank you for posting.

From the wikipedia page you linked to it looks like the mean for the negative binomial is coded correctly. 

Also, I checked against R because the underlying RMath library used here originated from R and I get very similar results to what you obtained:


```
> x <- seq(1, 10000)
> sum(dnbinom(x, 10, 0.2) * x)
[1] 40
```

I'm not sure what to make of it, but haven't had a chance to look closely yet. Perhaps another member of the team has an idea?

**Comment by octoscore** [comment]
Yes it is coded correctly for the pmf described in Wikipedia which is not the same parametric from than the one in your docstring. 
Your docstring is  p(x; r, p) = \binom{x + r - 1}{x} p^r (1 - p)^x and wikipedia is  p(x; r, p) = \binom{x + r - 1}{x} (1-p)^r (p)^x.

**Comment by danielcsaba** [comment]
Thanks for pointing this out. Yes, there is an inconsistency between the definition of the distribution and the formulae used to obtain its features. I'll take a closer look later today.

**Comment by danielcsaba** [comment]
I have updated the formulae so cloning the repo and reinstalling the package should solve the issue.

**Comment by jcr-lyxor** [comment]
thanks

**Comment by octoscore** [comment]
Thanks. Any chance to support floating size in order to use the negative binomial for poisson gamma mixture?  I think dnbinom_mu do it but it is not exposed.

Thank you
