### ISSUE TITLE
release v0.0.3

### ISSUE THREAD

**Issue by knaaptime** [QuantEcon/rvlib#24]
hey folks, thanks for putting this great package together. I have a few applications where drawing repeatedly in a for-loop is wayy faster using rvlib than scipy, so just wanted to drop by and say I'd be happy to offer what maintenance assistance i can here. I don't know any C, but i'm more than happy to help keep the Python nuts and bolts in order if it's of interest.

toward that end im curious if folks would be open to doing a small version bump to 0.0.3 and release to pypi (I can put the PR together)?  If so, I can help get a new version released on conda-forge that uses the new numba syntax (and hopefully get a build for windows working). I know there's not much active maintenance in the repo at the moment, so apologies if this is a bother

**Comment by jstac** [comment]
Hi @knaaptime, for my part I'd be delighted to have you involved and I believe @danielcsaba, the current maintainer, will feel the same.

In fact I think he would be glad to hand over the reins if you are willing to take them.

By the way, your research looks super interesting.  My knowledge of the field is very limited (about [this](https://python.quantecon.org/schelling.html) limited) but I like all kinds of high dimensional modeling problems.  I'm going to read some more and might be in touch by email if I have comments.

**Comment by danielcsaba** [comment]
Hi @knaaptime , indeed, I'd be happy to hand over the maintenance of the package and like the idea of the version bump!

**Comment by knaaptime** [comment]
awesome. And thanks for the kind words about my work; certainly if you have any thoughts, shoot me an email :)

Like I said, my C knowledge is basically nonexistent so it would be tough for me to take on the job solo, but I'm more than happy to join the team and help manage things on the Python side if you'd like to give me maintainer privileges or something. With a version bump we can do a new pypi release, which will get things sorted with conda-forge. Once the conda-forge machinery is working again I'll see if we can't get a version compiled for windows

**Comment by jstac** [comment]
That's great, thanks @knaaptime .  I'll send you an invite with maintainer privileges.

@mmcky and @sglyon , is there a way that we can coordinate to help @knaaptime maintain this package?  I honestly don't think there's much to be done --- just keeping the interface and distribution up to date --- and @knaaptime is willing to help us with that.

**Comment by mmcky** [comment]
this is wonderful news @knaaptime -- thanks for the help with this. Please let me know if there are any questions etc. I haven't had a large role to play in `rvlib` but I'm more than happy to link you to someone or find an answer etc. but @danielcsaba is the main lead on this project.

- [x] add @knaaptime as a maintainer to repo
- [ ] add @knaaptime as a maintainer on PyPI
- [x] add @knaaptime as a maintainer on conda-forge

**Comment by jstac** [comment]
@mmcky , thanks for your reply.  I believe @danielcsaba is very time constrained and would like to hand over the reins if possible.  I'm hoping @knaaptime will allow us to promote him to lead maintainer, with the provision that we all help out if anything curly comes in.

I envisage very low maintenance burden.

**Comment by knaaptime** [comment]
sounds good--we're on the same page. My sense is the C code is all pretty old and stable, and I can manage leading the other pieces. I can also probably recruit some help from folks like @jgaboardi and @sjsrey if need be

turns out the package wasnt actually released on pypi (so i went ahead and pushed my fork just to claim the package name. I'll probably delete that version and sync it back up with the canonical repo once the latest changes get merged and i get the build system worked out)


I've been tinkering a bit on a windows VM and managed to get compilation a bit further using mingw instead of MS build tools, so im still pretty optimistic on that front. I'm also working on a github action for [cibuildwheel](https://github.com/pypa/cibuildwheel) which may as well

**Comment by mmcky** [comment]
wonderful - thanks @knaaptime.

**Comment by knaaptime** [comment]
this should be all set folks (i had to bump two points to 0.0.5). I updated the [conda-forge recipe](https://github.com/conda-forge/rvlib-feedstock/pull/14) which should publish builds for all platforms now. If @danielcsaba or @sglyon wouldn't mind merging over there (i'm also added as a recipe maintainer in that PR) we should be good to go :)

**Comment by jstac** [comment]
Many thanks @knaaptime, over to you @danielcsaba or @sglyon, thanks in advance.

**Comment by danielcsaba** [comment]
Thanks @knaaptime, I merged the updated recipe for conda-forge

**Comment by knaaptime** [comment]
sweet, great teamwork folks
