### ISSUE TITLE
Add credit to README

### ISSUE THREAD

**Issue by synapticarbors** [QuantEcon/rvlib#7]
I was just looking at new packages that were being prepped on conda-forge and came across rvlib. It's a neat package, but I couldn't help but notice that it appears to have been bootstrapped from code I wrote from this repo:

https://github.com/synapticarbors/rmath-cffi-example

and appearing in the following blog posts:
- http://nbviewer.jupyter.org/github/synapticarbors/rmath-cffi-example/blob/master/rmath-cffi-example.ipynb
- https://www.continuum.io/blog/developer-blog/calling-c-libraries-numba-using-cffi

The connection seems pretty obvious from looking at the first commit on rvlib (https://github.com/QuantEcon/rvlib/commit/97d951b1725db731de70792967a05fb2465eb584). Technically, I didn't put a license in my repo, so by default  ["nobody else may reproduce, distribute, or create derivative works from your work"](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license). 

I like contributing to open source software and was thinking about extending my example to a complete package (but hadn't gotten around to it), so all I really ask is that at a minimum you put something in the README saying that this library was inspired by my work and that I contributed basically the build script to set up the cffi interface, since that was taken pretty much wholesale with the simple extension of adding more functions from Rmath to the cdef.

Hopefully you find this reasonable, and I'm willing to discuss any of this further if needed.

**Comment by danielcsaba** [comment]
Hi @synapticarbors,

we all fully agree and would like to apologize for not having credited you on the README already. This was unintentional and we will correct for it asap. `rvlib` was obviously inspired by your posts and builds on the build script you mention.

Would you be comfortable with the following lines in the README?

"The package was inspired by [posts](https://www.continuum.io/blog/developer-blog/calling-c-libraries-numba-using-cffi) written by Joshua Adelman (@synapticarbors) and utilizes his build script to set up the `cffi` interface."

Please extend this in any way you find reasonable.

Thanks and sorry for the inconvenience again.

**Comment by synapticarbors** [comment]
Hi @danielcsaba. I appreciate the quick reply. The language generally sounds good. I modified it slightly in https://github.com/QuantEcon/rvlib/issues/8

Also no worries about the oversight. I've forgotten to cite an important paper in an academic paper before and I wish correcting the issue was as easy as pushing a commit to github. Thanks again for addressing this.

**Comment by synapticarbors** [comment]
Closed by #8
